#!/bin/bash

# Copy frozen PDFs to nbloomf.md
cp -r $HOME/documents/classes/ca/freeze/*       $HOME/documents/nbloomf.md/pdf/classes/ca
cp -r $HOME/documents/classes/abstract/freeze/* $HOME/documents/nbloomf.md/pdf/classes/aa
cp -r $HOME/documents/classes/geom/freeze/*     $HOME/documents/nbloomf.md/pdf/classes/geom

# Build nbloomf.github.io and copy files
(cd $HOME/documents/nbloomf.md; make site && make move)

echo -e "\033[0;32mSuccessfully built nbloomf.github.io.\033[0m"
