#!/bin/bash

# Copy frozen PDFs to nbloomf.md
cp -r $HOME/documents/classes/coal/pdf/* $HOME/documents/nbloomf.md/pdf/classes/coal
cp -r $HOME/documents/classes/ring/pdf/* $HOME/documents/nbloomf.md/pdf/classes/ring
cp -r $HOME/documents/classes/geom/pdf/* $HOME/documents/nbloomf.md/pdf/classes/geom
cp -r $HOME/documents/classes/calc/pdf/* $HOME/documents/nbloomf.md/pdf/classes/calc
cp -r $HOME/documents/classes/stat/pdf/* $HOME/documents/nbloomf.md/pdf/classes/stat
cp -r $HOME/documents/classes/prfs/pdf/* $HOME/documents/nbloomf.md/pdf/classes/prfs

# Build nbloomf.github.io and copy files
(cd $HOME/documents/nbloomf.md; make site && make move)

echo -e "\033[0;32mSuccessfully built nbloomf.github.io.\033[0m"
