#!/bin/bash

REPOS="$HOME/documents/classes
$HOME/documents/nbloomf.md
$HOME/documents/nbloomf.github.io
$HOME/code/feivel
$HOME/code/carl
$HOME/code/munge
$HOME/code/work.scripts
$HOME/code/shell.struct
$HOME/fvl.lib/kreb-scout"

changes=0
pushes=0

for repo in $REPOS
do
  if [[ -n $(cd "$repo"; git status -s) ]];
    then
      echo "Uncommitted changes in $repo" | doppler lightyellow
      changes=1;
    else
      if [[ -n $(cd "$repo"; git cherry) ]];
        then
          echo "Unpushed commits in $repo" | doppler lightred
          pushes=1;
      fi
  fi
done


if ((changes == 0)); then
  echo "No uncommitted changes" | doppler lightblue
fi

if ((pushes == 0)); then
  echo "No unpushed commits" | doppler lightgreen
fi
